version: "3.9"

services:
  susunjadwal-backend-rmq-stg:
    image: rabbitmq:management-alpine
    restart: unless-stopped
    ports:
      - "15671-15672:15671-15672"
    networks:
      - public-web

  susunjadwal-backend-mongo-stg:
    image: mongo:7
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root-user
      MONGO_INITDB_ROOT_PASSWORD: root-user
      MONGO_INITDB_USERNAME: user
      MONGO_INITDB_PASSWORD: user
      MONGO_INITDB_DATABASE: backend
    volumes:
      - sunjad_db:/data/db
    networks:
      - public-web

  susunjadwal-backend-server-stg:
    image: ristekoss/susunjadwal-backend:staging
    labels:
      caddy: api-stg.susunjadwal.ristek.cs.ui.ac.id
      caddy.reverse_proxy: "{{upstreams 8000}}"
    restart: unless-stopped
    depends_on:
      - rmq-stg
      - mongo-stg
    volumes:
      - ./.env:/app/.env:ro
    ports:
      - 8005:8005
    networks:
      - public-web

networks:
  public-web:
    external: true

volumes:
  sunjad_db: