version: "3.9"

services:
  rmq-stg:
    image: rabbitmq:management-alpine
    restart: unless-stopped
    ports:
      - "15671-15672:15671-15672"
    networks:
      - public-web

  mongo-stg:
    image: mongo:7
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root-user
      MONGO_INITDB_ROOT_PASSWORD: root-user
      MONGO_INITDB_USERNAME: user
      MONGO_INITDB_PASSWORD: user
      MONGO_INITDB_DATABASE: backend
    volumes:
      - sunjad_db:/data/db
    networks:
      - public-web

  server-stg:
    # pull_policy: always
    image: ristekoss/susunjadwal-backend:staging
    # build:
    #   dockerfile: Dockerfile
    #   context: ..
    labels:
      caddy: api-stg.susunjadwal.cs.ui.ac.id
      caddy.reverse_proxy: "{{upstreams 8006}}"
    restart: unless-stopped
    depends_on:
      - rmq-stg
      - mongo-stg
    volumes:
      - ./.env:/opt/app/.env:ro
    ports:
      - 8006:8006
    networks:
      - public-web

networks:
  public-web:
    external: true

volumes:
  sunjad_db: